### ISSUE TITLE
TestShadowState_SetStateUsingBulkInsertion fails

### ISSUE THREAD

**Issue by petr-hanzl** [Fantom-foundation/Aida#1059]
Combination of `carmen` and `geth` `TestShadowState_SetStateUsingBulkInsertion` fails but error is not checked properly.

`Geth` produces an empty hash while `carmen` produces a correct hash.

**Comment by wsodsong** [comment]
@petr-hanzl has this issue been fixed?

**Comment by petr-hanzl** [comment]
Yes
