### ISSUE TITLE
Carmen's data race detection test fails due to issue in Carmen adaptor

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Aida#1107]
Carmen's [RaceDetection](https://scala.fantom.network/job/Carmen/job/Race-Detection) test is currently failing presumably due to a race condition detected in Aida's Carmen adaptor. An example log of a failed test case can be found [here](https://scala.fantom.network/job/Carmen/job/Race-Detection/35/console).

**Comment by petr-hanzl** [comment]
This issue got already fixed in this [PR](https://github.com/Fantom-foundation/Aida/pull/1090/files). The reason why the run failed is because current `main` does not have this fix.
@wsodsong are we merging develop into main anytime soon?
