### ISSUE TITLE
Fix code scanning alert - Incorrect conversion between integer types

### ISSUE THREAD

**Issue by wsodsong** [Fantom-foundation/Aida#1109]
Tracking issue for:
- [ ] https://github.com/Fantom-foundation/Aida/security/code-scanning/1
- [ ] https://github.com/Fantom-foundation/Aida/security/code-scanning/2

**Comment by rpl-ffl** [comment]
Incoming string range 0-2**64, but converted to int32 eventually.

https://codeql.github.com/codeql-query-help/go/go-incorrect-integer-conversion/
```
func parseAllocateGood4(wanted string) int32 {
	parsed, err := strconv.ParseInt(wanted, 10, 64)
	if err != nil {
		panic(err)
	}
	// GOOD: check for lower and uppper bounds
	if parsed > 0 && parsed <= math.MaxInt32 {
		return int32(parsed)
	}
	return DefaultAllocate
}
```
