### ISSUE TITLE
Lfvm on ethereum protobuf dataset

### ISSUE THREAD

**Issue by matejmode** [Fantom-foundation/Aida#1180]
After using protobuf dataset and confirming that ` --vm-impl geth` works correctly for whole range. Then running` --vm-impl lfvm`  returned these errors.

## Usage
Branch: `develop`
```
aida-vm --validate --chainid 1 --workers 1 --evm-impl aida-geth --vm-impl lfvm --aida-db rr0.4.substate.ethereum.13-14M --substate-encoding pb  13735140 13735140
```

# After Paris fork (transition to PoS)
All blocks after `15_537_394` are failing (vm gas config is probably incorrect).

```
world-state output error at block 15537394 tx 0;   Failed to validate balance for account 0x00000000000357848314F068fECA5D42e878a1d9
    have 5731278617347499170
    want 3718218632201979149
  Failed to validate storage for account 0x9ACf7474a5b54E99c1Ff2737919e3A2DFFE72253, key 0x000000000000000000000000000000000000000000000000000000000000000c
    have 0x0000000000000000000000000000000000000000000000000000000000000000
    want 0xa86c2e601b6c44eb4848f7d23d9df3113fbcac42041c49cbed5000cb4f118777
  Failed to validate balance for account 0xeEE27662c2B8EBa3CD936A23F039F3189633e4C8
    have 35102708387352264758
    want 37115534417566290944
```

# Blocks failing between Istanbul and Paris forks (`9_069_000`-`15_537_394`)
## Block `13_735_140`
```
world-state output error at block 13735140 tx 54;   Failed to validate balance for account 0x829BD824B016326A401d083B33D092293333A830
    have 1135767928239265971759
    want 1135767969489265971759
  Failed to validate balance for account 0x288F3683ca38a9945Cb4F76EE91f313Da2D31657
    have 335865273581922208
    want 332805605153847208
```

## Block `14_340_503`
```
live-db-validator err:
world-state output error at block 14340503 tx 38;   Account 0x8D3f545CaD8eDf345c3AdEf9bD04E0B44d112348 does not exist
  Failed to validate nonce for account 0x8D3f545CaD8eDf345c3AdEf9bD04E0B44d112348
    have 0
    want 1
  Failed to validate code for account 0x8D3f545CaD8eDf345c3AdEf9bD04E0B44d112348
    have len 0
    want len 11813
  Failed to validate storage for account 0x8D3f545CaD8eDf345c3AdEf9bD04E0B44d112348, key 0xef7259c50e8d9c6e7b45cf671de3b619c2c9d71d976f67f653dac37cc5b21bdd
    have 0x0000000000000000000000000000000000000000000000000000000000000000
    want 0x0000000000000000000000000000000000000000000000000000000000000001
  Failed to validate storage for account 0x8D3f545CaD8eDf345c3AdEf9bD04E0B44d112348, key 0x01b504967e35f21d4dc49da54d9de84fc74ff251157649cc334c604d54407e2f
    have 0x0000000000000000000000000000000000000000000000000000000000000000
    want 0x0000000000000000000000000000000000000000000000000000000000000001
 ...
 ...
 ...
```

## Block `15_025_981`
```
world-state output error at block 15025981 tx 45;   Account 0x1FF835478883203184898A30231d8fAF8a3ef5B3 does not exist
  Failed to validate nonce for account 0x1FF835478883203184898A30231d8fAF8a3ef5B3
    have 0
    want 1
  Failed to validate code for account 0x1FF835478883203184898A30231d8fAF8a3ef5B3
    have len 0
    want len 13295
  Failed to validate storage for account 0x1FF835478883203184898A30231d8fAF8a3ef5B3, key 0x8d1108e10bcb7c27dddfc02ed9d693a074039d026cf4ea4240b40f7d581ac809
    have 0x0000000000000000000000000000000000000000000000000000000000000000
    want 0x18e71a041afc1b2518db1a1418531b24196d1afd18571b0d19631a341b3c1b34
  Failed to validate storage for account 0x1FF835478883203184898A30231d8fAF8a3ef5B3, key 0xbb8a6a4669ba250d26cd7a459eca9d215f8307e33aebe50379bc5a3617ec344b
    have 0x0000000000000000000000000000000000000000000000000000000000000000
    want 0x1502190b0b5508e91a5203f41220151913bb0f2e1ac20afd04cd0b8c1055068f
 ...
 ...
 ...
 
```

# Datasets 
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.13_735_130-13_735_150.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.14_340_493-14_340_513.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.15_025_971-15_025_991.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.15_537_384-15_537_404.tar.gz

https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.13_803_446-13_803_466.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.14_953_159-14_953_179.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.15_039_441-15_039_461.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.15_427_788-15_427_808.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.15_039_441-15_039_461.tar.gz
https://storage.googleapis.com/aida-repository-public/geth-protobuf/subranges/substate.ethereum.15_445_471-15_445_491.tar.gz

https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.0-10M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.10-11M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.11-12M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.12-13M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.13-14M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.14-15M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.15-15.5M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.15.5-16M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.16-16.5M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.16.5-17M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.17-17.5M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.4.substate.ethereum.17.5-18M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.5.substate.ethereum.18-18.5M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.5.substate.ethereum.18.5-19M.tar.zst
https://storage.googleapis.com/aida-repository-public/geth-protobuf/rr0.5.substate.ethereum.19-19.5M.tar.zst

**Comment by simonlechner** [comment]
Thank you for finding these! We will have a look where they come from.

**Comment by matejmode** [comment]
After checking the rest of the blocks in each failing protobuf dataset, I found these blocks are also failing:
`13803456`
`14953169`
`15039451`
`15427798`
`15445161`
`15445481`

**Comment by simonlechner** [comment]
The LFVM uses a uint16 program counter with a range from 0 to 65535. Starting with the Shanghai revision and [eip-3860](https://eips.ethereum.org/EIPS/eip-3860) the init code size is limited to 49152 which is twice the maximum code size and smaller than the maximum of the program counter.

The following blocks can not be processed with the LFVM due to an overflow of the jump to argument:
13803456
14340503
14953169
15025981
15427798
15445161
15445481
